#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
$APPDIR/java/bin/java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/FFTGYROTestTool.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/grafica.jar" FFTGYROTestTool "$@"
